import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1',50000))
s.send('SAVE'.encode('utf-8'))
s.send('file1'.encode('utf-8'))
s.send('text line'.encode('utf-8'))
s.close()
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1',50000))
s.send('SAVE'.encode('utf-8'))
s.send('file2'.encode('utf-8'))
s.send('text line'.encode('utf-8'))
s.close()
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1',50000))
s.send('LOAD'.encode('utf-8'))
s.send('file3'.encode('utf-8'))
data = s.recv(1024).decode()
print(data)
s.close()
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1',50000))
s.send('LOAD'.encode('utf-8'))
s.send('file2'.encode('utf-8'))
data = s.recv(1024).decode()
print(data)
s.close()
